name: Build

on:
  push:
    branches: [ main ]
  pull_request:

env:
  ANDROID_NDK_VERSION: "25.2.9519653"

jobs:

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install libraries
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet

      - name: Build Windows
        run: |
          haxelib run lime build windows -release

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: MakerEngine-Windows
          path: export/release/windows/bin


  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            clang \
            libc++-dev \
            libc++abi-dev \
            libstdc++-12-dev

      - name: Install Haxe libraries
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          sdkmanager "ndk;${{ env.ANDROID_NDK_VERSION }}"

      - name: Configure Lime for Android
        run: |
          printf "%s\n" \
            "$ANDROID_HOME" \
            "$ANDROID_HOME/ndk/${{ env.ANDROID_NDK_VERSION }}" \
            "$JAVA_HOME" \
            "33" \
            "21" \
          | haxelib run lime setup android

      - name: Build Android
        run: |
          haxelib run lime build android -release

      - name: Upload Android
        uses: actions/upload-artifact@v4
        with:
          name: MakerEngine-Android
          path: export/release/android/bin