name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install hxcpp --quiet

      - name: Setup Lime
        run: |
          haxelib run lime setup

      - name: Build Windows
        run: |
          haxelib run lime build windows -release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MakerEngine-Windows
          path: export/windows/bin

  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Linux build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang libstdc++-12-dev

      - name: Install Haxe libraries
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install hxcpp --quiet
          haxelib install extension-androidtools --quiet

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          sdkmanager "ndk;25.2.9519653"

      - name: Set Android environment
        run: |
          echo "ANDROID_SDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Setup Lime Android
        run: |
          haxelib run lime setup android

      - name: Build Android
        run: |
          haxelib run lime build android -release

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MakerEngine-Android
          path: export/android/bin